### ISSUE TITLE
Ability to mark results as 'final' or 'confirmed'

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/ResultsRecorder#6]
_From @symroe on March 24, 2016 10:0_

LGiU users can confirm a result, meaning that they have verified it to be true at that point in time.

This should stop us asking for more results to be recorded for this authority.

_Copied from original issue: DemocracyClub/WhoCanIVoteFor#10_

**Comment by lamby** [comment]
I've called this "verify". Happy to change the verb, of course.
