### ISSUE TITLE
LGiU user group

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/ResultsRecorder#7]
_From @symroe on March 24, 2016 9:58_

This is a login role that will give LGiU staff to do particular things. on the site.

User account can be created by a user with staff status, and login can be very basic (this is a one off set of users, who need to be authrnticated for a couple of weeks at most).

_Copied from original issue: DemocracyClub/WhoCanIVoteFor#9_

**Comment by lamby** [comment]
We have (non-Twitter!) logins, etc. since 1ef68ed244894fb1c9b1c0b26bce9cab8bb057da
